library(dplyr)
MCMPG <- read.csv(file='MechaCar_mpg.csv')
head(MCMPG)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data =MCMPG)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data =MCMPG))
